nelmio_cors:
    defaults:
        allow_origin: []
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/':
            allow_origin: ['https://technova-frontend.onrender.com','http://localhost:5173']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
